version: "3.4"

services:
  web:
    build:
      context: .
      args:
        - TARGET_CONFIG_SET_NAME=${TARGET_CONFIG_SET_NAME}

    env_file:
      - docker_configs/${TARGET_CONFIG_SET_NAME}/docker_env/pg_creds.env
    environment:
      - PORT=5000

    depends_on:
      - db

    ports:
      - "0.0.0.0:5000:5000/tcp"

  db:
    image: postgres:12-alpine
    env_file:
      - docker_configs/${TARGET_CONFIG_SET_NAME}/docker_env/pg_creds.env
